# =============================================================================
# DETECTION SETTINGS
# =============================================================================
# Variable names to look for and analyze (empty list means analyze all variables)
variable_contexts = [
    "query",
    "sql",
    "statement",
]
# Function names to analyze SQL within (empty list means analyze all functions)
function_contexts = []
# Class method names to analyze SQL within (empty list means analyze all methods)
class_contexts = []
# Minimum string length of an sql string to analyse
min_sql_length = 10
# Whether contexts (function names, variable names...) are case-sensitive
case_sensitive = false

# =============================================================================
# FILE PROCESSING
# =============================================================================
# File patterns to look for in the specified `targets`
file_patterns = [
    "*.py",
    "*.pyi",
    "*.ipynb",
]
# File name patterns to exclude from analysis
exclude_patterns = []
# Whether file matching will respect git ignore
respect_gitignore = true
# Whether file matching will respect global git ignore
respect_global_gitignore = false
# Whether file matching will respect git exclude
respect_git_exclude = true
# Whether to include hidden files in analysis
include_hidden_files = false

# =============================================================================
# PERFORMANCE SETTINGS
# =============================================================================
# Enable parallel processing for better performance
parallel_processing = true
# Maximum number of worker threads (0 = auto-detect based on CPU cores)
max_threads = 0
# Number of files to process per thread batch
thread_chunk_size = 5

# =============================================================================
# INCREMENTAL MODE
# =============================================================================
# Only analyze files changed since last run (requires git)
incremental_mode = false
# Git branch to compare against for incremental mode
baseline_branch = "main"
# Include staged but uncommitted changes in incremental mode
include_staged = true

# =============================================================================
# OUTPUT SETTINGS
# =============================================================================
# Verbose output will include all levels of information except for debug information
verbose = false
# Quiet output will ignore normal output
quiet = false
# Debug output will include detailed debugging information
debug = false

# =============================================================================
# SQL PARSING SETTINGS
# =============================================================================
# Placeholders that will be replaced with values for SQL parsing
param_markers = [
    "?",
]
# String mappings to fix common SQL dialect differences
[dialect_mappings]
"NOTNULL" = "NOT NULL"
"ISNULL" = "IS NULL"
