[package]
name = "finder"
version = "0.0.0"
edition = "2024"

[dependencies]
logging.workspace = true
regex.workspace = true
rustpython-parser.workspace = true
serde.workspace = true
globset.workspace = true
rangemap = "1.5.1"
