# Variable names to look for and analyze
variable_names = [
    "_query",
    "_sql",
    "query",
    "sql",
    "statement",
    "cmd",
    "command",
    "sql_query",
    "db_query",
    "select_query",
    "insert_query",
    "update_query",
    "delete_query",
]

# Directories to look through for files matching `file_patterns`
targets = ["."]

# File patterns to look for in the specified `targets`
file_patterns = [
    "*.py",
    "*.pyi",
    "*.ipynb",
]
# File name patterns to exclude from analysis
exclude_patterns = []

# Contexts to exclude from analysis TODO: Specify a manual reference link
ignore_contexts = []

# Minimum string length of an sql string to analyse
min_sql_length = 10

# Whether contexts (function names, variable names...) are case-sensitive
case_sensitive = false

# Verbose output will include all levels of information except for debug information
verbose = false

# Quiet output will ignore 
quiet = false

# Whether file matching will respect git ignore
respect_gitignore = true
